# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_invoice.ui'
#
# Created: Fri May 10 22:03:44 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(831, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 70))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.edtInvStart = QtGui.QLineEdit(self.frame)
        self.edtInvStart.setGeometry(QtCore.QRect(80, 41, 120, 20))
        self.edtInvStart.setObjectName(_fromUtf8("edtInvStart"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(210, 41, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.edtInvEnd = QtGui.QLineEdit(self.frame)
        self.edtInvEnd.setGeometry(QtCore.QRect(240, 41, 120, 20))
        self.edtInvEnd.setObjectName(_fromUtf8("edtInvEnd"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 41, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 12, 51, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cbxInvQueryTypes = QtGui.QComboBox(self.frame)
        self.cbxInvQueryTypes.setGeometry(QtCore.QRect(80, 12, 151, 22))
        self.cbxInvQueryTypes.setObjectName(_fromUtf8("cbxInvQueryTypes"))
        self.btnInvQuery = QtGui.QPushButton(self.frame)
        self.btnInvQuery.setGeometry(QtCore.QRect(372, 40, 75, 23))
        self.btnInvQuery.setObjectName(_fromUtf8("btnInvQuery"))
        self.edtInvFilterText = QtGui.QLineEdit(self.frame)
        self.edtInvFilterText.setGeometry(QtCore.QRect(244, 12, 305, 20))
        self.edtInvFilterText.setText(_fromUtf8(""))
        self.edtInvFilterText.setObjectName(_fromUtf8("edtInvFilterText"))
        self.btnInvExport = QtGui.QPushButton(self.frame)
        self.btnInvExport.setGeometry(QtCore.QRect(456, 40, 75, 23))
        self.btnInvExport.setObjectName(_fromUtf8("btnInvExport"))
        self.btnInvCancel = QtGui.QPushButton(self.frame)
        self.btnInvCancel.setGeometry(QtCore.QRect(540, 40, 75, 23))
        self.btnInvCancel.setObjectName(_fromUtf8("btnInvCancel"))
        self.btnInvRed = QtGui.QPushButton(self.frame)
        self.btnInvRed.setEnabled(True)
        self.btnInvRed.setGeometry(QtCore.QRect(708, 8, 75, 23))
        self.btnInvRed.setCheckable(False)
        self.btnInvRed.setObjectName(_fromUtf8("btnInvRed"))
        self.ckInvCanceled = QtGui.QCheckBox(self.frame)
        self.ckInvCanceled.setGeometry(QtCore.QRect(572, 16, 73, 16))
        self.ckInvCanceled.setObjectName(_fromUtf8("ckInvCanceled"))
        self.btnInvPrint = QtGui.QPushButton(self.frame)
        self.btnInvPrint.setEnabled(True)
        self.btnInvPrint.setGeometry(QtCore.QRect(624, 40, 75, 23))
        self.btnInvPrint.setCheckable(False)
        self.btnInvPrint.setObjectName(_fromUtf8("btnInvPrint"))
        self.verticalLayout_2.addWidget(self.frame)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.tvInvMain = QtGui.QTreeWidget(self.frame_3)
        self.tvInvMain.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvInvMain.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvInvMain.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvInvMain.setObjectName(_fromUtf8("tvInvMain"))
        self.tvInvMain.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tvInvMain)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.tvInvGoods = QtGui.QTreeWidget(self.frame_2)
        self.tvInvGoods.setObjectName(_fromUtf8("tvInvGoods"))
        self.tvInvGoods.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_3.addWidget(self.tvInvGoods)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.frame_8 = QtGui.QFrame(self.tab_3)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.label_28 = QtGui.QLabel(self.frame_8)
        self.label_28.setGeometry(QtCore.QRect(10, 12, 51, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.cbxDocQueryTypes = QtGui.QComboBox(self.frame_8)
        self.cbxDocQueryTypes.setGeometry(QtCore.QRect(80, 12, 151, 22))
        self.cbxDocQueryTypes.setObjectName(_fromUtf8("cbxDocQueryTypes"))
        self.btnDocQuery = QtGui.QPushButton(self.frame_8)
        self.btnDocQuery.setGeometry(QtCore.QRect(268, 44, 75, 23))
        self.btnDocQuery.setObjectName(_fromUtf8("btnDocQuery"))
        self.edtDocFilterText = QtGui.QLineEdit(self.frame_8)
        self.edtDocFilterText.setGeometry(QtCore.QRect(240, 12, 291, 20))
        self.edtDocFilterText.setText(_fromUtf8(""))
        self.edtDocFilterText.setObjectName(_fromUtf8("edtDocFilterText"))
        self.btnDocDel = QtGui.QPushButton(self.frame_8)
        self.btnDocDel.setGeometry(QtCore.QRect(180, 44, 75, 23))
        self.btnDocDel.setObjectName(_fromUtf8("btnDocDel"))
        self.btnDocImport = QtGui.QPushButton(self.frame_8)
        self.btnDocImport.setGeometry(QtCore.QRect(4, 44, 75, 23))
        self.btnDocImport.setObjectName(_fromUtf8("btnDocImport"))
        self.btnTodayDoc = QtGui.QPushButton(self.frame_8)
        self.btnTodayDoc.setEnabled(False)
        self.btnTodayDoc.setGeometry(QtCore.QRect(356, 44, 75, 23))
        self.btnTodayDoc.setFlat(False)
        self.btnTodayDoc.setObjectName(_fromUtf8("btnTodayDoc"))
        self.btnDocInvoice = QtGui.QPushButton(self.frame_8)
        self.btnDocInvoice.setGeometry(QtCore.QRect(92, 44, 75, 23))
        self.btnDocInvoice.setObjectName(_fromUtf8("btnDocInvoice"))
        self.verticalLayout_10.addWidget(self.frame_8)
        self.splitter_3 = QtGui.QSplitter(self.tab_3)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.frame_9 = QtGui.QFrame(self.splitter_3)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_29 = QtGui.QLabel(self.frame_9)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_9.addWidget(self.label_29)
        self.tvDocMain = QtGui.QTreeWidget(self.frame_9)
        self.tvDocMain.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvDocMain.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvDocMain.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvDocMain.setObjectName(_fromUtf8("tvDocMain"))
        self.tvDocMain.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_9.addWidget(self.tvDocMain)
        self.frame_7 = QtGui.QFrame(self.splitter_3)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_25 = QtGui.QLabel(self.frame_7)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_8.addWidget(self.label_25)
        self.tvDocGoods = QtGui.QTreeWidget(self.frame_7)
        self.tvDocGoods.setObjectName(_fromUtf8("tvDocGoods"))
        self.tvDocGoods.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_8.addWidget(self.tvDocGoods)
        self.verticalLayout_10.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(8, 16, 625, 165))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 26, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edtCorpName = QtGui.QLineEdit(self.groupBox)
        self.edtCorpName.setGeometry(QtCore.QRect(128, 20, 361, 20))
        self.edtCorpName.setObjectName(_fromUtf8("edtCorpName"))
        self.edtTaxcode = QtGui.QLineEdit(self.groupBox)
        self.edtTaxcode.setGeometry(QtCore.QRect(128, 48, 361, 20))
        self.edtTaxcode.setObjectName(_fromUtf8("edtTaxcode"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 54, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.edtAddress = QtGui.QLineEdit(self.groupBox)
        self.edtAddress.setGeometry(QtCore.QRect(128, 76, 361, 20))
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 82, 97, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.edtBank = QtGui.QLineEdit(self.groupBox)
        self.edtBank.setGeometry(QtCore.QRect(128, 104, 361, 20))
        self.edtBank.setObjectName(_fromUtf8("edtBank"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 110, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.edtBranchNo = QtGui.QLineEdit(self.groupBox)
        self.edtBranchNo.setGeometry(QtCore.QRect(128, 132, 277, 20))
        self.edtBranchNo.setObjectName(_fromUtf8("edtBranchNo"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(20, 138, 54, 12))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.btnSave = QtGui.QPushButton(self.tab_2)
        self.btnSave.setGeometry(QtCore.QRect(16, 424, 75, 23))
        self.btnSave.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);"))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(8, 320, 625, 89))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.ckReadDocAuto = QtGui.QCheckBox(self.groupBox_3)
        self.ckReadDocAuto.setGeometry(QtCore.QRect(12, 24, 177, 16))
        self.ckReadDocAuto.setObjectName(_fromUtf8("ckReadDocAuto"))
        self.btnReadDir = QtGui.QPushButton(self.groupBox_3)
        self.btnReadDir.setGeometry(QtCore.QRect(12, 52, 75, 23))
        self.btnReadDir.setObjectName(_fromUtf8("btnReadDir"))
        self.edtReadDocDir = QtGui.QLineEdit(self.groupBox_3)
        self.edtReadDocDir.setGeometry(QtCore.QRect(128, 52, 465, 20))
        self.edtReadDocDir.setObjectName(_fromUtf8("edtReadDocDir"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(8, 196, 625, 113))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 58, 81, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.ckSyncToServer = QtGui.QCheckBox(self.groupBox_2)
        self.ckSyncToServer.setEnabled(False)
        self.ckSyncToServer.setGeometry(QtCore.QRect(424, 20, 173, 16))
        self.ckSyncToServer.setObjectName(_fromUtf8("ckSyncToServer"))
        self.edtServerAddress = QtGui.QLineEdit(self.groupBox_2)
        self.edtServerAddress.setGeometry(QtCore.QRect(128, 22, 277, 20))
        self.edtServerAddress.setObjectName(_fromUtf8("edtServerAddress"))
        self.edtServerPort = QtGui.QLineEdit(self.groupBox_2)
        self.edtServerPort.setGeometry(QtCore.QRect(128, 52, 277, 20))
        self.edtServerPort.setObjectName(_fromUtf8("edtServerPort"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(20, 28, 81, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.btnSyncManual = QtGui.QPushButton(self.groupBox_2)
        self.btnSyncManual.setGeometry(QtCore.QRect(420, 78, 75, 23))
        self.btnSyncManual.setStyleSheet(_fromUtf8("background-color:rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);"))
        self.btnSyncManual.setObjectName(_fromUtf8("btnSyncManual"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 84, 85, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.edtUnupload = QtGui.QLineEdit(self.groupBox_2)
        self.edtUnupload.setGeometry(QtCore.QRect(128, 80, 277, 20))
        self.edtUnupload.setObjectName(_fromUtf8("edtUnupload"))
        self.btnResetClear = QtGui.QPushButton(self.tab_2)
        self.btnResetClear.setGeometry(QtCore.QRect(12, 468, 121, 23))
        self.btnResetClear.setObjectName(_fromUtf8("btnResetClear"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.edtLogMemo = QtGui.QTextEdit(self.tab_4)
        self.edtLogMemo.setGeometry(QtCore.QRect(16, 20, 605, 477))
        self.edtLogMemo.setObjectName(_fromUtf8("edtLogMemo"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "增值税开票系统", None))
        self.edtInvStart.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtInvStart.setText(_translate("MainWindow", "2012-02-10", None))
        self.label_6.setText(_translate("MainWindow", "到", None))
        self.edtInvEnd.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtInvEnd.setText(_translate("MainWindow", "2013-06-10", None))
        self.label_5.setText(_translate("MainWindow", "开票时间", None))
        self.label_4.setText(_translate("MainWindow", "查询类型", None))
        self.btnInvQuery.setText(_translate("MainWindow", "查询", None))
        self.btnInvExport.setText(_translate("MainWindow", "导出", None))
        self.btnInvCancel.setText(_translate("MainWindow", "作 废", None))
        self.btnInvRed.setText(_translate("MainWindow", "红 冲", None))
        self.ckInvCanceled.setText(_translate("MainWindow", "已作废", None))
        self.btnInvPrint.setText(_translate("MainWindow", "打 印", None))
        self.label_2.setText(_translate("MainWindow", "发票主体信息", None))
        self.label.setText(_translate("MainWindow", "商品项信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发票管理", None))
        self.label_28.setText(_translate("MainWindow", "查询类型", None))
        self.btnDocQuery.setText(_translate("MainWindow", "查询", None))
        self.btnDocDel.setText(_translate("MainWindow", "订单删除", None))
        self.btnDocImport.setText(_translate("MainWindow", "订单导入", None))
        self.btnTodayDoc.setText(_translate("MainWindow", "当日订单", None))
        self.btnDocInvoice.setText(_translate("MainWindow", "订单开票", None))
        self.label_29.setText(_translate("MainWindow", "订单主体信息", None))
        self.label_25.setText(_translate("MainWindow", "商品项信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "订单管理", None))
        self.groupBox.setTitle(_translate("MainWindow", "企业信息", None))
        self.label_3.setText(_translate("MainWindow", "企业名称", None))
        self.label_7.setText(_translate("MainWindow", "税号", None))
        self.label_8.setText(_translate("MainWindow", "企业地址和电话", None))
        self.label_9.setText(_translate("MainWindow", "银行账号", None))
        self.label_15.setText(_translate("MainWindow", "分机号", None))
        self.btnSave.setText(_translate("MainWindow", "保存", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "开票模式", None))
        self.ckReadDocAuto.setText(_translate("MainWindow", "自动读取订单", None))
        self.btnReadDir.setText(_translate("MainWindow", "设定目录", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据同步", None))
        self.label_17.setText(_translate("MainWindow", "服务器端口", None))
        self.ckSyncToServer.setText(_translate("MainWindow", "自动同步", None))
        self.edtServerAddress.setText(_translate("MainWindow", "192.168.0.1", None))
        self.edtServerPort.setText(_translate("MainWindow", "8080", None))
        self.label_16.setText(_translate("MainWindow", "服务器地址", None))
        self.btnSyncManual.setText(_translate("MainWindow", "同步", None))
        self.label_18.setText(_translate("MainWindow", "未上传发票数", None))
        self.btnResetClear.setText(_translate("MainWindow", "reset clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "系统设置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "运行日志", None))
        self.miUserMgr.setText(_translate("MainWindow", "用户管理", None))
        self.miTask.setText(_translate("MainWindow", "计划任务", None))
        self.miServerStatus.setText(_translate("MainWindow", "服务器状态", None))
        self.miChangePwd.setText(_translate("MainWindow", "更改用户密码", None))
        self.miExit.setText(_translate("MainWindow", "系统退出", None))

