# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_invoice_export.ui'
#
# Created: Sat Mar 16 02:14:40 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(895, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 70))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.edtStart = QtGui.QLineEdit(self.frame)
        self.edtStart.setGeometry(QtCore.QRect(80, 46, 120, 20))
        self.edtStart.setObjectName(_fromUtf8("edtStart"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(210, 46, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.edtEnd = QtGui.QLineEdit(self.frame)
        self.edtEnd.setGeometry(QtCore.QRect(240, 46, 120, 20))
        self.edtEnd.setObjectName(_fromUtf8("edtEnd"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 46, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 12, 51, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cbxQueryTypes = QtGui.QComboBox(self.frame)
        self.cbxQueryTypes.setGeometry(QtCore.QRect(70, 10, 151, 22))
        self.cbxQueryTypes.setObjectName(_fromUtf8("cbxQueryTypes"))
        self.btnQuery = QtGui.QPushButton(self.frame)
        self.btnQuery.setGeometry(QtCore.QRect(370, 46, 75, 23))
        self.btnQuery.setObjectName(_fromUtf8("btnQuery"))
        self.edtFilterText = QtGui.QLineEdit(self.frame)
        self.edtFilterText.setGeometry(QtCore.QRect(240, 10, 291, 20))
        self.edtFilterText.setText(_fromUtf8(""))
        self.edtFilterText.setObjectName(_fromUtf8("edtFilterText"))
        self.btnExport = QtGui.QPushButton(self.frame)
        self.btnExport.setGeometry(QtCore.QRect(584, 46, 75, 23))
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.ckSaveToExportDir = QtGui.QCheckBox(self.frame)
        self.ckSaveToExportDir.setGeometry(QtCore.QRect(680, 48, 153, 16))
        self.ckSaveToExportDir.setObjectName(_fromUtf8("ckSaveToExportDir"))
        self.btnUpload = QtGui.QPushButton(self.frame)
        self.btnUpload.setGeometry(QtCore.QRect(456, 45, 117, 25))
        self.btnUpload.setObjectName(_fromUtf8("btnUpload"))
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(632, 8, 51, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.cbxUploadStatus = QtGui.QComboBox(self.frame)
        self.cbxUploadStatus.setGeometry(QtCore.QRect(608, 8, 151, 22))
        self.cbxUploadStatus.setObjectName(_fromUtf8("cbxUploadStatus"))
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(548, 10, 51, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_2.addWidget(self.frame)
        self.labStatus = QtGui.QLabel(self.tab)
        self.labStatus.setObjectName(_fromUtf8("labStatus"))
        self.verticalLayout_2.addWidget(self.labStatus)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.tvMain = QtGui.QTreeWidget(self.frame_3)
        self.tvMain.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvMain.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvMain.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvMain.setObjectName(_fromUtf8("tvMain"))
        self.tvMain.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tvMain)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.tvGoods = QtGui.QTreeWidget(self.frame_2)
        self.tvGoods.setObjectName(_fromUtf8("tvGoods"))
        self.tvGoods.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_3.addWidget(self.tvGoods)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.btnImportInvoice = QtGui.QPushButton(self.tab_3)
        self.btnImportInvoice.setGeometry(QtCore.QRect(16, 56, 75, 23))
        self.btnImportInvoice.setObjectName(_fromUtf8("btnImportInvoice"))
        self.edtEndImport = QtGui.QLineEdit(self.tab_3)
        self.edtEndImport.setGeometry(QtCore.QRect(246, 28, 120, 20))
        self.edtEndImport.setObjectName(_fromUtf8("edtEndImport"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(16, 28, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.edtStartImport = QtGui.QLineEdit(self.tab_3)
        self.edtStartImport.setGeometry(QtCore.QRect(86, 28, 120, 20))
        self.edtStartImport.setObjectName(_fromUtf8("edtStartImport"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(216, 28, 31, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(16, 100, 409, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 132, 54, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lb_tips = QtGui.QLabel(self.tab_3)
        self.lb_tips.setGeometry(QtCore.QRect(16, 152, 377, 121))
        self.lb_tips.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0);\n"
"font: 12pt \"微软雅黑\";"))
        self.lb_tips.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lb_tips.setText(_fromUtf8(""))
        self.lb_tips.setWordWrap(True)
        self.lb_tips.setObjectName(_fromUtf8("lb_tips"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(4, 12, 625, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 36, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edtCorpName = QtGui.QLineEdit(self.groupBox)
        self.edtCorpName.setGeometry(QtCore.QRect(128, 30, 361, 20))
        self.edtCorpName.setObjectName(_fromUtf8("edtCorpName"))
        self.edtTaxcode = QtGui.QLineEdit(self.groupBox)
        self.edtTaxcode.setGeometry(QtCore.QRect(128, 58, 361, 20))
        self.edtTaxcode.setObjectName(_fromUtf8("edtTaxcode"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 64, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.edtAddress = QtGui.QLineEdit(self.groupBox)
        self.edtAddress.setGeometry(QtCore.QRect(128, 86, 361, 20))
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 92, 97, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.edtBank = QtGui.QLineEdit(self.groupBox)
        self.edtBank.setGeometry(QtCore.QRect(128, 114, 361, 20))
        self.edtBank.setObjectName(_fromUtf8("edtBank"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btnSave = QtGui.QPushButton(self.groupBox)
        self.btnSave.setGeometry(QtCore.QRect(20, 148, 75, 23))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(124, 148, 345, 16))
        self.label_16.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0);\n"
"\n"
"font: 9pt \"微软雅黑\";\n"
""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(8, 200, 621, 253))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(296, 16, 345, 16))
        self.label_10.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0);\n"
"\n"
"font: 9pt \"微软雅黑\";\n"
""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tvClients = QtGui.QTreeWidget(self.groupBox_2)
        self.tvClients.setGeometry(QtCore.QRect(12, 40, 601, 201))
        self.tvClients.setObjectName(_fromUtf8("tvClients"))
        self.tvClients.headerItem().setText(0, _fromUtf8("1"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(16, 20, 713, 429))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "发票认证输出 v1.4.0.0", None))
        self.edtStart.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtStart.setText(_translate("MainWindow", "2012-02-10", None))
        self.label_6.setText(_translate("MainWindow", "到", None))
        self.edtEnd.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtEnd.setText(_translate("MainWindow", "2013-06-10", None))
        self.label_5.setText(_translate("MainWindow", "开票时间", None))
        self.label_4.setText(_translate("MainWindow", "查询类型", None))
        self.btnQuery.setText(_translate("MainWindow", "查询", None))
        self.btnExport.setText(_translate("MainWindow", "导出", None))
        self.ckSaveToExportDir.setText(_translate("MainWindow", "自动保存到输出目录", None))
        self.btnUpload.setText(_translate("MainWindow", "上传到服务器", None))
        self.label_17.setText(_translate("MainWindow", "查询类型", None))
        self.label_18.setText(_translate("MainWindow", "上传状态", None))
        self.labStatus.setText(_translate("MainWindow", "  状态", None))
        self.label_2.setText(_translate("MainWindow", "发票主体信息", None))
        self.label.setText(_translate("MainWindow", "商品项信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发票信息", None))
        self.btnImportInvoice.setText(_translate("MainWindow", "导入", None))
        self.edtEndImport.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtEndImport.setText(_translate("MainWindow", "2013-06-10", None))
        self.label_11.setText(_translate("MainWindow", "开票时间", None))
        self.edtStartImport.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtStartImport.setText(_translate("MainWindow", "2012-02-10", None))
        self.label_12.setText(_translate("MainWindow", "到", None))
        self.label_13.setText(_translate("MainWindow", "导入发票之前请开启开票软件，并切换到开票主界面", None))
        self.label_14.setText(_translate("MainWindow", "提示", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "导入发票", None))
        self.groupBox.setTitle(_translate("MainWindow", "企业信息", None))
        self.label_3.setText(_translate("MainWindow", "企业名称", None))
        self.label_7.setText(_translate("MainWindow", "税号", None))
        self.label_8.setText(_translate("MainWindow", "企业地址和电话", None))
        self.label_9.setText(_translate("MainWindow", "银行账号", None))
        self.btnSave.setText(_translate("MainWindow", "保存", None))
        self.label_16.setText(_translate("MainWindow", "以上信息请务必填写正确，否则将导致认证数据失败", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "客户授权信息(您可以发送发票给以下客户)", None))
        self.label_10.setText(_translate("MainWindow", "请将客户授权文件 *.lic 放置 license目录下", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "系统设置", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff0000;\">系统简介</span></p><p><span style=\" font-size:12pt;\">1、通过截屏技术实现增值税发票数据导出，并转换成税务进项发票认证导入数据，实现进项发票认证电子化，实时、高效的完成进行发票认证、汇总统计。</span></p><p><span style=\" font-size:12pt;\">进项发票认证电子化：</span></p><p><span style=\" font-size:12pt;\">2、增值税防伪开票系统直接导出已开发票数据，导入认证系统；通过实现进项发票认证电子化，替代了目前进项发票手工扫描的过程，大大减少了进项发票认证工作量。</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">实时、高效：</span></p><p><span style=\" font-size:12pt;\">发票开具后可实时导出进项认证数据，并可即时导入购方认证系统；可实时获得进项发票数据，有利于进项发票数据汇总、统计；为购销双方的发票数据传递提供了一个实时、高效、安全的通道</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">系统流程</span></p><p><span style=\" font-size:12pt;\">1、供应商开具增值税发票后，利用《发票导出》软件导出成电子发票数据，并通过购方提供的Email地址发送给购方。</span></p><p><span style=\" font-size:12pt;\">2、购方利用《发票接收》软件接收电子发票数据，电子发票数据存储在数据库中。</span></p><p><span style=\" font-size:12pt;\">3、当收到供应商纸质发票后，购方核对发票后直接传送给远程认证软件做远程认证。</span></p><p><span style=\" font-size:12pt;\">4、购方支付系统可以从电子发票数据库获取电子发票数据，以此作为供应商付款凭证。</span></p><p><span style=\" font-size:12pt;\">5、可对进项发票数据进行简单查询、统计并打印报表。</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "说明", None))
        self.miUserMgr.setText(_translate("MainWindow", "用户管理", None))
        self.miTask.setText(_translate("MainWindow", "计划任务", None))
        self.miServerStatus.setText(_translate("MainWindow", "服务器状态", None))
        self.miChangePwd.setText(_translate("MainWindow", "更改用户密码", None))
        self.miExit.setText(_translate("MainWindow", "系统退出", None))

