# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_invoice_import.ui'
#
# Created: Fri Mar 15 22:56:00 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(871, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.edtStart = QtGui.QLineEdit(self.frame)
        self.edtStart.setGeometry(QtCore.QRect(80, 50, 120, 20))
        self.edtStart.setObjectName(_fromUtf8("edtStart"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(210, 50, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.edtEnd = QtGui.QLineEdit(self.frame)
        self.edtEnd.setGeometry(QtCore.QRect(240, 50, 120, 20))
        self.edtEnd.setObjectName(_fromUtf8("edtEnd"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 12, 51, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cbxQueryTypes = QtGui.QComboBox(self.frame)
        self.cbxQueryTypes.setGeometry(QtCore.QRect(70, 10, 151, 22))
        self.cbxQueryTypes.setObjectName(_fromUtf8("cbxQueryTypes"))
        self.btnQuery = QtGui.QPushButton(self.frame)
        self.btnQuery.setGeometry(QtCore.QRect(370, 50, 75, 23))
        self.btnQuery.setObjectName(_fromUtf8("btnQuery"))
        self.edtFilterText = QtGui.QLineEdit(self.frame)
        self.edtFilterText.setGeometry(QtCore.QRect(240, 10, 291, 20))
        self.edtFilterText.setText(_fromUtf8(""))
        self.edtFilterText.setObjectName(_fromUtf8("edtFilterText"))
        self.btnExport = QtGui.QPushButton(self.frame)
        self.btnExport.setGeometry(QtCore.QRect(460, 50, 133, 23))
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.ckSaveToExportDir = QtGui.QCheckBox(self.frame)
        self.ckSaveToExportDir.setGeometry(QtCore.QRect(556, 12, 153, 16))
        self.ckSaveToExportDir.setObjectName(_fromUtf8("ckSaveToExportDir"))
        self.btnAddToSelectList = QtGui.QPushButton(self.frame)
        self.btnAddToSelectList.setGeometry(QtCore.QRect(604, 48, 133, 23))
        self.btnAddToSelectList.setObjectName(_fromUtf8("btnAddToSelectList"))
        self.btnDel = QtGui.QPushButton(self.frame)
        self.btnDel.setGeometry(QtCore.QRect(744, 48, 75, 23))
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.verticalLayout_2.addWidget(self.frame)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.tvMain = QtGui.QTreeWidget(self.frame_3)
        self.tvMain.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvMain.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvMain.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvMain.setObjectName(_fromUtf8("tvMain"))
        self.tvMain.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tvMain)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.tvGoods = QtGui.QTreeWidget(self.frame_2)
        self.tvGoods.setObjectName(_fromUtf8("tvGoods"))
        self.tvGoods.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_3.addWidget(self.tvGoods)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_4 = QtGui.QFrame(self.tab_5)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.btnDel_SelectList = QtGui.QPushButton(self.frame_4)
        self.btnDel_SelectList.setGeometry(QtCore.QRect(96, 8, 75, 23))
        self.btnDel_SelectList.setObjectName(_fromUtf8("btnDel_SelectList"))
        self.btnExport_SelectList = QtGui.QPushButton(self.frame_4)
        self.btnExport_SelectList.setGeometry(QtCore.QRect(184, 8, 133, 23))
        self.btnExport_SelectList.setObjectName(_fromUtf8("btnExport_SelectList"))
        self.ckSaveToExportDir_SelectList = QtGui.QCheckBox(self.frame_4)
        self.ckSaveToExportDir_SelectList.setGeometry(QtCore.QRect(336, 12, 153, 16))
        self.ckSaveToExportDir_SelectList.setObjectName(_fromUtf8("ckSaveToExportDir_SelectList"))
        self.btnClearAll_SelectList = QtGui.QPushButton(self.frame_4)
        self.btnClearAll_SelectList.setGeometry(QtCore.QRect(8, 8, 75, 23))
        self.btnClearAll_SelectList.setObjectName(_fromUtf8("btnClearAll_SelectList"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(12, 40, 73, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lb_invoice_num = QtGui.QLabel(self.frame_4)
        self.lb_invoice_num.setGeometry(QtCore.QRect(104, 42, 54, 12))
        self.lb_invoice_num.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.lb_invoice_num.setObjectName(_fromUtf8("lb_invoice_num"))
        self.verticalLayout_7.addWidget(self.frame_4)
        self.splitter_2 = QtGui.QSplitter(self.tab_5)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame_5 = QtGui.QFrame(self.splitter_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_12 = QtGui.QLabel(self.frame_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.tvMain_SelectList = QtGui.QTreeWidget(self.frame_5)
        self.tvMain_SelectList.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvMain_SelectList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvMain_SelectList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvMain_SelectList.setObjectName(_fromUtf8("tvMain_SelectList"))
        self.tvMain_SelectList.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_5.addWidget(self.tvMain_SelectList)
        self.frame_6 = QtGui.QFrame(self.splitter_2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_16 = QtGui.QLabel(self.frame_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_6.addWidget(self.label_16)
        self.tvGoods_SelectList = QtGui.QTreeWidget(self.frame_6)
        self.tvGoods_SelectList.setObjectName(_fromUtf8("tvGoods_SelectList"))
        self.tvGoods_SelectList.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_6.addWidget(self.tvGoods_SelectList)
        self.verticalLayout_7.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.btnImportInvoice = QtGui.QPushButton(self.tab_3)
        self.btnImportInvoice.setGeometry(QtCore.QRect(20, 20, 245, 29))
        self.btnImportInvoice.setObjectName(_fromUtf8("btnImportInvoice"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(16, 100, 409, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 132, 54, 12))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lb_tips = QtGui.QLabel(self.tab_3)
        self.lb_tips.setGeometry(QtCore.QRect(16, 152, 733, 257))
        self.lb_tips.setStyleSheet(_fromUtf8("color:rgb(255, 0, 0);\n"
"font: 12pt \"微软雅黑\";"))
        self.lb_tips.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lb_tips.setText(_fromUtf8(""))
        self.lb_tips.setWordWrap(True)
        self.lb_tips.setObjectName(_fromUtf8("lb_tips"))
        self.btnImportInvoice_FromServer = QtGui.QPushButton(self.tab_3)
        self.btnImportInvoice_FromServer.setGeometry(QtCore.QRect(20, 60, 245, 29))
        self.btnImportInvoice_FromServer.setObjectName(_fromUtf8("btnImportInvoice_FromServer"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(288, 62, 51, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.cbxDownloadTime = QtGui.QComboBox(self.tab_3)
        self.cbxDownloadTime.setGeometry(QtCore.QRect(348, 60, 151, 22))
        self.cbxDownloadTime.setObjectName(_fromUtf8("cbxDownloadTime"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(4, 12, 625, 109))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 36, 54, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edtCorpName = QtGui.QLineEdit(self.groupBox)
        self.edtCorpName.setGeometry(QtCore.QRect(128, 30, 361, 20))
        self.edtCorpName.setObjectName(_fromUtf8("edtCorpName"))
        self.edtTaxcode = QtGui.QLineEdit(self.groupBox)
        self.edtTaxcode.setGeometry(QtCore.QRect(128, 58, 361, 20))
        self.edtTaxcode.setObjectName(_fromUtf8("edtTaxcode"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 64, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(8, 164, 509, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.btnReadLicense = QtGui.QPushButton(self.tab_2)
        self.btnReadLicense.setGeometry(QtCore.QRect(16, 132, 161, 23))
        self.btnReadLicense.setObjectName(_fromUtf8("btnReadLicense"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(16, 20, 713, 429))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "发票认证输入 v1.0.0.0", None))
        self.edtStart.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtStart.setText(_translate("MainWindow", "2012-02-10", None))
        self.label_6.setText(_translate("MainWindow", "到", None))
        self.edtEnd.setInputMask(_translate("MainWindow", "9999-99-99; ", None))
        self.edtEnd.setText(_translate("MainWindow", "2013-06-10", None))
        self.label_5.setText(_translate("MainWindow", "开票时间", None))
        self.label_4.setText(_translate("MainWindow", "查询类型", None))
        self.btnQuery.setText(_translate("MainWindow", "查询", None))
        self.btnExport.setText(_translate("MainWindow", "导出认证文件(XML)", None))
        self.ckSaveToExportDir.setText(_translate("MainWindow", "自动保存到输出目录", None))
        self.btnAddToSelectList.setText(_translate("MainWindow", "添加到选择列表", None))
        self.btnDel.setText(_translate("MainWindow", "删 除", None))
        self.label_2.setText(_translate("MainWindow", "发票主体信息", None))
        self.label.setText(_translate("MainWindow", "商品项信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发票信息", None))
        self.btnDel_SelectList.setText(_translate("MainWindow", "删除", None))
        self.btnExport_SelectList.setText(_translate("MainWindow", "导出认证文件(XML)", None))
        self.ckSaveToExportDir_SelectList.setText(_translate("MainWindow", "自动保存到输出目录", None))
        self.btnClearAll_SelectList.setText(_translate("MainWindow", "清空", None))
        self.label_9.setText(_translate("MainWindow", "发票数量", None))
        self.lb_invoice_num.setText(_translate("MainWindow", "0", None))
        self.label_12.setText(_translate("MainWindow", "发票主体信息", None))
        self.label_16.setText(_translate("MainWindow", "商品项信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "选择列表", None))
        self.btnImportInvoice.setText(_translate("MainWindow", "从文件导入开票信息", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>选择销货发票输出文件进行导入(*.ixe)</p></body></html>", None))
        self.label_14.setText(_translate("MainWindow", "提示", None))
        self.btnImportInvoice_FromServer.setText(_translate("MainWindow", "从服务器接收开票信息", None))
        self.label_10.setText(_translate("MainWindow", "时间范围", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "导入发票", None))
        self.groupBox.setTitle(_translate("MainWindow", "企业信息", None))
        self.label_3.setText(_translate("MainWindow", "企业名称", None))
        self.label_7.setText(_translate("MainWindow", "税号", None))
        self.label_8.setText(_translate("MainWindow", "请将客户授权文件 .lic 放置在 license目录内", None))
        self.btnReadLicense.setText(_translate("MainWindow", "读取客户授权信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "系统设置", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff0000;\">系统简介</span></p><p><span style=\" font-size:12pt;\">1、通过截屏技术实现增值税发票数据导出，并转换成税务进项发票认证导入数据，实现进项发票认证电子化，实时、高效的完成进行发票认证、汇总统计。</span></p><p><span style=\" font-size:12pt;\">进项发票认证电子化：</span></p><p><span style=\" font-size:12pt;\">2、增值税防伪开票系统直接导出已开发票数据，导入认证系统；通过实现进项发票认证电子化，替代了目前进项发票手工扫描的过程，大大减少了进项发票认证工作量。</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">实时、高效：</span></p><p><span style=\" font-size:12pt;\">发票开具后可实时导出进项认证数据，并可即时导入购方认证系统；可实时获得进项发票数据，有利于进项发票数据汇总、统计；为购销双方的发票数据传递提供了一个实时、高效、安全的通道</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">系统流程</span></p><p><span style=\" font-size:12pt;\">1、供应商开具增值税发票后，利用《发票导出》软件导出成电子发票数据，并通过购方提供的Email地址发送给购方。</span></p><p><span style=\" font-size:12pt;\">2、购方利用《发票接收》软件接收电子发票数据，电子发票数据存储在数据库中。</span></p><p><span style=\" font-size:12pt;\">3、当收到供应商纸质发票后，购方核对发票后直接传送给远程认证软件做远程认证。</span></p><p><span style=\" font-size:12pt;\">4、购方支付系统可以从电子发票数据库获取电子发票数据，以此作为供应商付款凭证。</span></p><p><span style=\" font-size:12pt;\">5、可对进项发票数据进行简单查询、统计并打印报表。</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "说明", None))
        self.miUserMgr.setText(_translate("MainWindow", "用户管理", None))
        self.miTask.setText(_translate("MainWindow", "计划任务", None))
        self.miServerStatus.setText(_translate("MainWindow", "服务器状态", None))
        self.miChangePwd.setText(_translate("MainWindow", "更改用户密码", None))
        self.miExit.setText(_translate("MainWindow", "系统退出", None))

