# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_invoice_export.ui'
#
# Created: Sat Aug 31 18:01:05 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(895, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.frame = QtGui.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 70))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(210, 46, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 46, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 12, 51, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cbxQueryTypes = QtGui.QComboBox(self.frame)
        self.cbxQueryTypes.setGeometry(QtCore.QRect(70, 10, 151, 22))
        self.cbxQueryTypes.setObjectName(_fromUtf8("cbxQueryTypes"))
        self.btnQuery = QtGui.QPushButton(self.frame)
        self.btnQuery.setGeometry(QtCore.QRect(624, 8, 75, 23))
        self.btnQuery.setObjectName(_fromUtf8("btnQuery"))
        self.edtFilterText = QtGui.QLineEdit(self.frame)
        self.edtFilterText.setGeometry(QtCore.QRect(240, 10, 377, 20))
        self.edtFilterText.setText(_fromUtf8(""))
        self.edtFilterText.setObjectName(_fromUtf8("edtFilterText"))
        self.btnExport = QtGui.QPushButton(self.frame)
        self.btnExport.setGeometry(QtCore.QRect(724, 8, 75, 23))
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.dtStart = QtGui.QDateTimeEdit(self.frame)
        self.dtStart.setGeometry(QtCore.QRect(72, 44, 125, 22))
        self.dtStart.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dtStart.setCalendarPopup(True)
        self.dtStart.setObjectName(_fromUtf8("dtStart"))
        self.dtEnd = QtGui.QDateTimeEdit(self.frame)
        self.dtEnd.setGeometry(QtCore.QRect(240, 44, 125, 22))
        self.dtEnd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dtEnd.setCalendarPopup(True)
        self.dtEnd.setObjectName(_fromUtf8("dtEnd"))
        self.cbxInvoiceTypes = QtGui.QComboBox(self.frame)
        self.cbxInvoiceTypes.setGeometry(QtCore.QRect(540, 44, 81, 22))
        self.cbxInvoiceTypes.setObjectName(_fromUtf8("cbxInvoiceTypes"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(508, 48, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(384, 48, 41, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cbxInvoiceStatus = QtGui.QComboBox(self.frame)
        self.cbxInvoiceStatus.setGeometry(QtCore.QRect(416, 44, 81, 22))
        self.cbxInvoiceStatus.setObjectName(_fromUtf8("cbxInvoiceStatus"))
        self.verticalLayout_4.addWidget(self.frame)
        self.tvMain = QtGui.QTreeWidget(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvMain.setFont(font)
        self.tvMain.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvMain.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvMain.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvMain.setObjectName(_fromUtf8("tvMain"))
        self.tvMain.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tvMain)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.tvGoods = QtGui.QTreeWidget(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvGoods.setFont(font)
        self.tvGoods.setObjectName(_fromUtf8("tvGoods"))
        self.tvGoods.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_3.addWidget(self.tvGoods)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(472, 28, 385, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(16, 172, 429, 313))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.edtRegText = QtGui.QTextEdit(self.groupBox_3)
        self.edtRegText.setGeometry(QtCore.QRect(16, 48, 405, 81))
        self.edtRegText.setObjectName(_fromUtf8("edtRegText"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 28, 54, 12))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.btnRegister = QtGui.QPushButton(self.groupBox_3)
        self.btnRegister.setGeometry(QtCore.QRect(16, 140, 75, 23))
        self.btnRegister.setObjectName(_fromUtf8("btnRegister"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 260, 397, 37))
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.edtUserInfo = QtGui.QTextEdit(self.groupBox_3)
        self.edtUserInfo.setGeometry(QtCore.QRect(16, 196, 401, 57))
        self.edtUserInfo.setObjectName(_fromUtf8("edtUserInfo"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 172, 177, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btnApplyReg = QtGui.QCommandLinkButton(self.groupBox_3)
        self.btnApplyReg.setGeometry(QtCore.QRect(260, 136, 161, 37))
        self.btnApplyReg.setObjectName(_fromUtf8("btnApplyReg"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(16, 16, 429, 133))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(276, 36, 29, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.cbxMonth = QtGui.QComboBox(self.groupBox)
        self.cbxMonth.setGeometry(QtCore.QRect(196, 32, 72, 22))
        self.cbxMonth.setObjectName(_fromUtf8("cbxMonth"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(172, 36, 29, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cbxYear = QtGui.QComboBox(self.groupBox)
        self.cbxYear.setGeometry(QtCore.QRect(92, 32, 72, 22))
        self.cbxYear.setObjectName(_fromUtf8("cbxYear"))
        self.btnExec = QtGui.QPushButton(self.groupBox)
        self.btnExec.setGeometry(QtCore.QRect(20, 70, 369, 29))
        self.btnExec.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 127);"))
        self.btnExec.setObjectName(_fromUtf8("btnExec"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(24, 36, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Genius-exp 税控发票输出", None))
        self.label_2.setText(_translate("MainWindow", "发票主体信息", None))
        self.label_6.setText(_translate("MainWindow", "到", None))
        self.label_5.setText(_translate("MainWindow", "开票时间", None))
        self.label_4.setText(_translate("MainWindow", "查询类型", None))
        self.btnQuery.setText(_translate("MainWindow", "查询", None))
        self.btnExport.setText(_translate("MainWindow", "导出", None))
        self.dtStart.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.dtEnd.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_7.setText(_translate("MainWindow", "类型", None))
        self.label_8.setText(_translate("MainWindow", "状态 ", None))
        self.label.setText(_translate("MainWindow", "商品项信息", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发票信息", None))
        self.label_13.setText(_translate("MainWindow", "导入发票之前请开启开票软件，并切换到开票主界面", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "注册信息", None))
        self.label_18.setText(_translate("MainWindow", "注册码", None))
        self.btnRegister.setText(_translate("MainWindow", "注册", None))
        self.label_16.setText(_translate("MainWindow", "未授权用户一次最多只能导入部分发票记录，如需导出全部记录请注册为授权用户", None))
        self.label_3.setText(_translate("MainWindow", "授权用户信息", None))
        self.btnApplyReg.setText(_translate("MainWindow", "申请为授权用户", None))
        self.groupBox.setTitle(_translate("MainWindow", "导出", None))
        self.label_19.setText(_translate("MainWindow", "月", None))
        self.label_12.setText(_translate("MainWindow", "年", None))
        self.btnExec.setText(_translate("MainWindow", "执 行", None))
        self.label_11.setText(_translate("MainWindow", "开票时间", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "导出发票", None))
        self.miUserMgr.setText(_translate("MainWindow", "用户管理", None))
        self.miTask.setText(_translate("MainWindow", "计划任务", None))
        self.miServerStatus.setText(_translate("MainWindow", "服务器状态", None))
        self.miChangePwd.setText(_translate("MainWindow", "更改用户密码", None))
        self.miExit.setText(_translate("MainWindow", "系统退出", None))

