# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_invoice.ui'
#
# Created: Tue May 28 23:25:32 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1049, 557)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.btnQuery_1 = QtGui.QPushButton(self.frame)
        self.btnQuery_1.setGeometry(QtCore.QRect(664, 12, 75, 23))
        self.btnQuery_1.setObjectName(_fromUtf8("btnQuery_1"))
        self.btnExport_1 = QtGui.QPushButton(self.frame)
        self.btnExport_1.setGeometry(QtCore.QRect(748, 12, 75, 23))
        self.btnExport_1.setObjectName(_fromUtf8("btnExport_1"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(444, 12, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cbxEmployee_1 = QtGui.QComboBox(self.frame)
        self.cbxEmployee_1.setGeometry(QtCore.QRect(500, 12, 153, 22))
        self.cbxEmployee_1.setEditable(True)
        self.cbxEmployee_1.setObjectName(_fromUtf8("cbxEmployee_1"))
        self.dtStart_1 = QtGui.QDateTimeEdit(self.frame)
        self.dtStart_1.setGeometry(QtCore.QRect(112, 12, 140, 22))
        self.dtStart_1.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.dtStart_1.setCalendarPopup(True)
        self.dtStart_1.setObjectName(_fromUtf8("dtStart_1"))
        self.dtEnd_1 = QtGui.QDateTimeEdit(self.frame)
        self.dtEnd_1.setGeometry(QtCore.QRect(280, 12, 140, 22))
        self.dtEnd_1.setCalendarPopup(True)
        self.dtEnd_1.setObjectName(_fromUtf8("dtEnd_1"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(260, 16, 29, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.cbxTimeQueryType1 = QtGui.QComboBox(self.frame)
        self.cbxTimeQueryType1.setGeometry(QtCore.QRect(0, 12, 105, 22))
        self.cbxTimeQueryType1.setObjectName(_fromUtf8("cbxTimeQueryType1"))
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.txtTotal_1 = QtGui.QLabel(self.frame_3)
        self.txtTotal_1.setObjectName(_fromUtf8("txtTotal_1"))
        self.verticalLayout_4.addWidget(self.txtTotal_1)
        self.tvList_1 = QtGui.QTreeWidget(self.frame_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvList_1.setFont(font)
        self.tvList_1.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_1.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_1.setObjectName(_fromUtf8("tvList_1"))
        self.tvList_1.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tvList_1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_2 = QtGui.QFrame(self.tab_3)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.cbxMechine_2 = QtGui.QComboBox(self.frame_2)
        self.cbxMechine_2.setGeometry(QtCore.QRect(500, 8, 153, 22))
        self.cbxMechine_2.setEditable(True)
        self.cbxMechine_2.setObjectName(_fromUtf8("cbxMechine_2"))
        self.btnExport_2 = QtGui.QPushButton(self.frame_2)
        self.btnExport_2.setGeometry(QtCore.QRect(748, 8, 75, 23))
        self.btnExport_2.setObjectName(_fromUtf8("btnExport_2"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(444, 8, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.btnQuery_2 = QtGui.QPushButton(self.frame_2)
        self.btnQuery_2.setGeometry(QtCore.QRect(664, 8, 75, 23))
        self.btnQuery_2.setObjectName(_fromUtf8("btnQuery_2"))
        self.dtStart_2 = QtGui.QDateTimeEdit(self.frame_2)
        self.dtStart_2.setGeometry(QtCore.QRect(114, 8, 140, 22))
        self.dtStart_2.setCalendarPopup(True)
        self.dtStart_2.setObjectName(_fromUtf8("dtStart_2"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(262, 12, 29, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dtEnd_2 = QtGui.QDateTimeEdit(self.frame_2)
        self.dtEnd_2.setGeometry(QtCore.QRect(282, 8, 140, 22))
        self.dtEnd_2.setCalendarPopup(True)
        self.dtEnd_2.setObjectName(_fromUtf8("dtEnd_2"))
        self.cbxTimeQueryType2 = QtGui.QComboBox(self.frame_2)
        self.cbxTimeQueryType2.setGeometry(QtCore.QRect(0, 8, 105, 22))
        self.cbxTimeQueryType2.setObjectName(_fromUtf8("cbxTimeQueryType2"))
        self.verticalLayout_7.addWidget(self.frame_2)
        self.txtTotal_2 = QtGui.QLabel(self.tab_3)
        self.txtTotal_2.setObjectName(_fromUtf8("txtTotal_2"))
        self.verticalLayout_7.addWidget(self.txtTotal_2)
        self.tvList_2 = QtGui.QTreeWidget(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvList_2.setFont(font)
        self.tvList_2.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_2.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_2.setObjectName(_fromUtf8("tvList_2"))
        self.tvList_2.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_7.addWidget(self.tvList_2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.btnExport_3 = QtGui.QPushButton(self.frame_4)
        self.btnExport_3.setGeometry(QtCore.QRect(492, 8, 75, 23))
        self.btnExport_3.setObjectName(_fromUtf8("btnExport_3"))
        self.label_13 = QtGui.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(6, 12, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.btnQuery_3 = QtGui.QPushButton(self.frame_4)
        self.btnQuery_3.setGeometry(QtCore.QRect(408, 8, 75, 23))
        self.btnQuery_3.setObjectName(_fromUtf8("btnQuery_3"))
        self.dtStart_3 = QtGui.QDateTimeEdit(self.frame_4)
        self.dtStart_3.setGeometry(QtCore.QRect(68, 8, 140, 22))
        self.dtStart_3.setCalendarPopup(True)
        self.dtStart_3.setObjectName(_fromUtf8("dtStart_3"))
        self.label_12 = QtGui.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(216, 12, 29, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.dtEnd_3 = QtGui.QDateTimeEdit(self.frame_4)
        self.dtEnd_3.setGeometry(QtCore.QRect(236, 8, 140, 22))
        self.dtEnd_3.setCalendarPopup(True)
        self.dtEnd_3.setObjectName(_fromUtf8("dtEnd_3"))
        self.verticalLayout_3.addWidget(self.frame_4)
        self.txtTotal_3 = QtGui.QLabel(self.tab_2)
        self.txtTotal_3.setObjectName(_fromUtf8("txtTotal_3"))
        self.verticalLayout_3.addWidget(self.txtTotal_3)
        self.tvList_3 = QtGui.QTreeWidget(self.tab_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvList_3.setFont(font)
        self.tvList_3.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_3.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_3.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_3.setObjectName(_fromUtf8("tvList_3"))
        self.tvList_3.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_3.addWidget(self.tvList_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_5 = QtGui.QFrame(self.tab_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(10, 13, 61, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.btnQuery_4 = QtGui.QPushButton(self.frame_5)
        self.btnQuery_4.setGeometry(QtCore.QRect(348, 8, 75, 23))
        self.btnQuery_4.setObjectName(_fromUtf8("btnQuery_4"))
        self.btnExport_4 = QtGui.QPushButton(self.frame_5)
        self.btnExport_4.setGeometry(QtCore.QRect(432, 8, 75, 23))
        self.btnExport_4.setObjectName(_fromUtf8("btnExport_4"))
        self.dtStart_4 = QtGui.QDateEdit(self.frame_5)
        self.dtStart_4.setGeometry(QtCore.QRect(81, 9, 113, 25))
        self.dtStart_4.setCalendarPopup(True)
        self.dtStart_4.setObjectName(_fromUtf8("dtStart_4"))
        self.dtEnd_4 = QtGui.QDateEdit(self.frame_5)
        self.dtEnd_4.setGeometry(QtCore.QRect(228, 8, 113, 25))
        self.dtEnd_4.setCalendarPopup(True)
        self.dtEnd_4.setObjectName(_fromUtf8("dtEnd_4"))
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(208, 12, 29, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_6.addWidget(self.frame_5)
        self.txtTotal_4 = QtGui.QLabel(self.tab_4)
        self.txtTotal_4.setObjectName(_fromUtf8("txtTotal_4"))
        self.verticalLayout_6.addWidget(self.txtTotal_4)
        self.tvList_4 = QtGui.QTreeWidget(self.tab_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvList_4.setFont(font)
        self.tvList_4.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_4.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_4.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_4.setObjectName(_fromUtf8("tvList_4"))
        self.tvList_4.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_6.addWidget(self.tvList_4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_6 = QtGui.QFrame(self.tab_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_16 = QtGui.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(9, 16, 61, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.btnQuery_5 = QtGui.QPushButton(self.frame_6)
        self.btnQuery_5.setGeometry(QtCore.QRect(347, 11, 75, 23))
        self.btnQuery_5.setObjectName(_fromUtf8("btnQuery_5"))
        self.btnExport_5 = QtGui.QPushButton(self.frame_6)
        self.btnExport_5.setGeometry(QtCore.QRect(431, 11, 75, 23))
        self.btnExport_5.setObjectName(_fromUtf8("btnExport_5"))
        self.dtEnd_5 = QtGui.QDateEdit(self.frame_6)
        self.dtEnd_5.setGeometry(QtCore.QRect(227, 11, 113, 25))
        self.dtEnd_5.setCalendarPopup(True)
        self.dtEnd_5.setObjectName(_fromUtf8("dtEnd_5"))
        self.label_17 = QtGui.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(207, 15, 29, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.dtStart_5 = QtGui.QDateEdit(self.frame_6)
        self.dtStart_5.setGeometry(QtCore.QRect(80, 12, 113, 25))
        self.dtStart_5.setCalendarPopup(True)
        self.dtStart_5.setObjectName(_fromUtf8("dtStart_5"))
        self.verticalLayout_5.addWidget(self.frame_6)
        self.txtTotal_5 = QtGui.QLabel(self.tab_5)
        self.txtTotal_5.setObjectName(_fromUtf8("txtTotal_5"))
        self.verticalLayout_5.addWidget(self.txtTotal_5)
        self.tvList_5 = QtGui.QTreeWidget(self.tab_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.tvList_5.setFont(font)
        self.tvList_5.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_5.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_5.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_5.setObjectName(_fromUtf8("tvList_5"))
        self.tvList_5.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_5.addWidget(self.tvList_5)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame_7 = QtGui.QFrame(self.widget)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.btnExport_6 = QtGui.QPushButton(self.frame_7)
        self.btnExport_6.setGeometry(QtCore.QRect(924, 8, 75, 23))
        self.btnExport_6.setObjectName(_fromUtf8("btnExport_6"))
        self.label_18 = QtGui.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(6, 12, 61, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.btnQuery_6 = QtGui.QPushButton(self.frame_7)
        self.btnQuery_6.setGeometry(QtCore.QRect(840, 8, 75, 23))
        self.btnQuery_6.setObjectName(_fromUtf8("btnQuery_6"))
        self.dtStart_6 = QtGui.QDateTimeEdit(self.frame_7)
        self.dtStart_6.setGeometry(QtCore.QRect(68, 8, 140, 22))
        self.dtStart_6.setCalendarPopup(True)
        self.dtStart_6.setObjectName(_fromUtf8("dtStart_6"))
        self.label_19 = QtGui.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(216, 12, 29, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.dtEnd_6 = QtGui.QDateTimeEdit(self.frame_7)
        self.dtEnd_6.setGeometry(QtCore.QRect(236, 8, 140, 22))
        self.dtEnd_6.setCalendarPopup(True)
        self.dtEnd_6.setObjectName(_fromUtf8("dtEnd_6"))
        self.cbxEmployee_6 = QtGui.QComboBox(self.frame_7)
        self.cbxEmployee_6.setGeometry(QtCore.QRect(672, 8, 153, 22))
        self.cbxEmployee_6.setEditable(True)
        self.cbxEmployee_6.setObjectName(_fromUtf8("cbxEmployee_6"))
        self.label_7 = QtGui.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(616, 8, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cbxMechine_6 = QtGui.QComboBox(self.frame_7)
        self.cbxMechine_6.setGeometry(QtCore.QRect(448, 8, 153, 22))
        self.cbxMechine_6.setEditable(True)
        self.cbxMechine_6.setObjectName(_fromUtf8("cbxMechine_6"))
        self.label_22 = QtGui.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(392, 8, 61, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_9.addWidget(self.frame_7)
        self.txtTotal_6 = QtGui.QLabel(self.widget)
        self.txtTotal_6.setText(_fromUtf8(""))
        self.txtTotal_6.setObjectName(_fromUtf8("txtTotal_6"))
        self.verticalLayout_9.addWidget(self.txtTotal_6)
        self.tvList_6 = QtGui.QTreeWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tvList_6.setFont(font)
        self.tvList_6.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_6.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_6.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_6.setObjectName(_fromUtf8("tvList_6"))
        self.tvList_6.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_9.addWidget(self.tvList_6)
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.frame_8 = QtGui.QFrame(self.tab_6)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.btnExport_7 = QtGui.QPushButton(self.frame_8)
        self.btnExport_7.setGeometry(QtCore.QRect(492, 8, 75, 23))
        self.btnExport_7.setObjectName(_fromUtf8("btnExport_7"))
        self.label_20 = QtGui.QLabel(self.frame_8)
        self.label_20.setGeometry(QtCore.QRect(6, 12, 61, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.btnQuery_7 = QtGui.QPushButton(self.frame_8)
        self.btnQuery_7.setGeometry(QtCore.QRect(408, 8, 75, 23))
        self.btnQuery_7.setObjectName(_fromUtf8("btnQuery_7"))
        self.dtStart_7 = QtGui.QDateTimeEdit(self.frame_8)
        self.dtStart_7.setGeometry(QtCore.QRect(68, 8, 140, 22))
        self.dtStart_7.setCalendarPopup(True)
        self.dtStart_7.setObjectName(_fromUtf8("dtStart_7"))
        self.label_21 = QtGui.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(216, 12, 29, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.dtEnd_7 = QtGui.QDateTimeEdit(self.frame_8)
        self.dtEnd_7.setGeometry(QtCore.QRect(236, 8, 140, 22))
        self.dtEnd_7.setCalendarPopup(True)
        self.dtEnd_7.setObjectName(_fromUtf8("dtEnd_7"))
        self.verticalLayout_8.addWidget(self.frame_8)
        self.txtTotal_7 = QtGui.QLabel(self.tab_6)
        self.txtTotal_7.setObjectName(_fromUtf8("txtTotal_7"))
        self.verticalLayout_8.addWidget(self.txtTotal_7)
        self.tvList_7 = QtGui.QTreeWidget(self.tab_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tvList_7.setFont(font)
        self.tvList_7.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tvList_7.setAlternatingRowColors(True)
        self.tvList_7.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tvList_7.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvList_7.setObjectName(_fromUtf8("tvList_7"))
        self.tvList_7.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_8.addWidget(self.tvList_7)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.miUserMgr = QtGui.QAction(MainWindow)
        self.miUserMgr.setObjectName(_fromUtf8("miUserMgr"))
        self.miTask = QtGui.QAction(MainWindow)
        self.miTask.setObjectName(_fromUtf8("miTask"))
        self.miServerStatus = QtGui.QAction(MainWindow)
        self.miServerStatus.setObjectName(_fromUtf8("miServerStatus"))
        self.miChangePwd = QtGui.QAction(MainWindow)
        self.miChangePwd.setObjectName(_fromUtf8("miChangePwd"))
        self.miExit = QtGui.QAction(MainWindow)
        self.miExit.setObjectName(_fromUtf8("miExit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "大众开票统计", None))
        self.btnQuery_1.setText(_translate("MainWindow", "查询", None))
        self.btnExport_1.setText(_translate("MainWindow", "导出", None))
        self.label_6.setText(_translate("MainWindow", "收银员", None))
        self.dtStart_1.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.dtEnd_1.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label.setText(_translate("MainWindow", "至", None))
        self.txtTotal_1.setText(_translate("MainWindow", "合计:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发票日报表-收银员", None))
        self.btnExport_2.setText(_translate("MainWindow", "导出", None))
        self.label_10.setText(_translate("MainWindow", "机器号", None))
        self.btnQuery_2.setText(_translate("MainWindow", "查询", None))
        self.dtStart_2.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_3.setText(_translate("MainWindow", "至", None))
        self.dtEnd_2.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.txtTotal_2.setText(_translate("MainWindow", "合计:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "发票日报表-机器", None))
        self.btnExport_3.setText(_translate("MainWindow", "导出", None))
        self.label_13.setText(_translate("MainWindow", "结算日期", None))
        self.btnQuery_3.setText(_translate("MainWindow", "查询", None))
        self.dtStart_3.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_12.setText(_translate("MainWindow", "至", None))
        self.dtEnd_3.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.txtTotal_3.setText(_translate("MainWindow", "合计:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "汇总报表-机器结算日", None))
        self.label_14.setText(_translate("MainWindow", "开票日期", None))
        self.btnQuery_4.setText(_translate("MainWindow", "查询", None))
        self.btnExport_4.setText(_translate("MainWindow", "导出", None))
        self.label_15.setText(_translate("MainWindow", "至", None))
        self.txtTotal_4.setText(_translate("MainWindow", "合计:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "汇总报表-机器开票日", None))
        self.label_16.setText(_translate("MainWindow", "开票日期", None))
        self.btnQuery_5.setText(_translate("MainWindow", "查询", None))
        self.btnExport_5.setText(_translate("MainWindow", "导出", None))
        self.label_17.setText(_translate("MainWindow", "至", None))
        self.txtTotal_5.setText(_translate("MainWindow", "合计:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "作废汇总表", None))
        self.btnExport_6.setText(_translate("MainWindow", "导出", None))
        self.label_18.setText(_translate("MainWindow", "结算日期", None))
        self.btnQuery_6.setText(_translate("MainWindow", "查询", None))
        self.dtStart_6.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_19.setText(_translate("MainWindow", "至", None))
        self.dtEnd_6.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_7.setText(_translate("MainWindow", "收银员", None))
        self.label_22.setText(_translate("MainWindow", "机器号", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "收银员收银日报表", None))
        self.btnExport_7.setText(_translate("MainWindow", "导出", None))
        self.label_20.setText(_translate("MainWindow", "结算日期", None))
        self.btnQuery_7.setText(_translate("MainWindow", "查询", None))
        self.dtStart_7.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_21.setText(_translate("MainWindow", "至", None))
        self.dtEnd_7.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.txtTotal_7.setText(_translate("MainWindow", "合计:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "收银员收银汇总日报表", None))
        self.miUserMgr.setText(_translate("MainWindow", "用户管理", None))
        self.miTask.setText(_translate("MainWindow", "计划任务", None))
        self.miServerStatus.setText(_translate("MainWindow", "服务器状态", None))
        self.miChangePwd.setText(_translate("MainWindow", "更改用户密码", None))
        self.miExit.setText(_translate("MainWindow", "系统退出", None))

